### ISSUE TITLE
Where to get the pangya client (the actual game)?

### ISSUE THREAD

**Issue by pakLebah** [hsreina/pangya-server#14]
I've been searching all over the internet to get pangya, but it all ends up to dead links. Do you have the latest client game? Please share it with us through google drive. Thank you.

**Comment by luismk** [comment]
Is files backup
https://drive.google.com/drive/mobile/folders/0B_RaG0yzITpIVlI4NzhMQnhaMm8

**Comment by luismk** [comment]
Is my backup + files: https://drive.google.com/folderview?id=1QeEsEh0D3HaA9tmIzPijDxQtSlAOXh9R

**Comment by pakLebah** [comment]
Thank you. But there are so many files in your folder. I got lost. Is there any instruction which files need to be installed and the order of installation? All I want is to play it offline or against the computer.

**Comment by luismk** [comment]
there is no installation order
but you can normally install the files.
about running offline you can use projectG unpacked or packed

I am very busy to help you, but look on youtube or on forums

**Comment by hsreina** [comment]
Not an issue related to the server. Closing it.
